Language: objective-c
xcode_workspace: Request.xcworkspace
xcode_scheme: RequestTests
xcode_destination: platform=iOS Simulator,OS=13.1,name=iPhone 8
osx_image: xcode11.3.1

after_success:
  - bash <(curl -s https://codecov.io/bash)
